

map<string,string> filenames = {
                   {"zb0", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias0pbpb.root"},
		   {"zb1", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias1pbpb.root"},
		   {"zb2", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias2pbpb.root"},
		   {"zb3", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias3pbpb.root"},
		   {"zb4", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias4pbpb.root"},
		   {"zb5", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias5pbpb.root"},
		   {"zb6", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias6pbpb.root"},
		   {"zb7", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias7pbpb.root"},
		   {"zb8", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias8pbpb.root"},
		   {"zb9", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias9pbpb.root"},
		   {"zb10", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias10pbpb.root"},
		   {"zb11", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias11pbpb.root"},
		   {"zb12", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias12pbpb.root"},
		   {"zb13", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias13pbpb.root"},
		   {"zb14", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias14pbpb.root"},
		   {"zb15", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias15pbpb.root"},
		   {"zb16", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias16pbpb.root"},
		   {"zb17", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias17pbpb.root"},
		   {"zb18", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias18pbpb.root"},
		   {"zb19", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias19pbpb.root"},
		   {"HP", "/eos/user/l/lamartik/run3_pprefpbpbreco_data_05072024.root"},
		   {"MC", "/eos/cms/store/group/phys_heavyions/lamartik/tuples/MC_pprefwpbpbreco_privateforjec.root"},
		   {"localHP", "testdata/run3_pprefpbpbreco_data_05072024.root"},
		   /*{"zb0", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias0pbpb.root"},
		   {"zb1", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias1pbpb.root"},
		   {"zb2", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias2pbpb.root"},
		   {"zb3", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias3pbpb.root"},
		   {"zb4", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias4pbpb.root"},
		   {"zb5", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias5pbpb.root"},
		   {"zb6", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias6pbpb.root"},
		   {"zb7", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias7pbpb.root"},
		   {"zb8", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias8pbpb.root"},
		   {"zb9", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias9pbpb.root"},
		   {"zb10", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias10pbpb.root"},
		   {"zb11", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias11pbpb.root"},
		   {"zb12", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias12pbpb.root"},
		   {"zb13", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias13pbpb.root"},
		   {"zb14", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias14pbpb.root"},
		   {"zb15", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias15pbpb.root"},
		   {"zb16", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias16pbpb.root"},
		   {"zb17", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias17pbpb.root"},
		   {"zb18", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias18pbpb.root"},
		   {"zb19", "/eos/user/l/lamartik/HIJEC_ZEROBIAS_TUPLES/zerobias19pbpb.root"},*/
		   {"RERECOHP", "/eos/user/l/lamartik/HIJECRERECO/HP2023-pbpbreco.root"},
		   {"RERECOMC", "/eos/user/l/lamartik/HIJECRERECO/MC2023-pbpbreco.root"}

                    };
